/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/Minesweeper 
 *
 * modified     20201110
 * date         20201104
 * @filename	LoseScreen.java
 * @author      hkamal
 * @version     1.0
 * @see         Lose screen
 */

package minesweeper;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.imageio.ImageIO;

public class LoseScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoseScreen
     */
    public LoseScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endGame = new javax.swing.JLabel();
        mineImage = new javax.swing.JLabel();
        loseText = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();
        company = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.WHITE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    	int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
    	int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
    	this.setLocation(x, y);

        endGame.setFont(new java.awt.Font("DigifaceWide", 0, 80)); // NOI18N
        endGame.setForeground(new java.awt.Color(255, 0, 0));
        endGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endGame.setText("Game Over");

        mineImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        try {
            mineImage.setIcon(new javax.swing.ImageIcon(ImageIO.read(getClass().getResourceAsStream("assets/bomb-lose.png")))); // http://www.sireasgallery.com/icon/minesweeper/Mine3
        }
        catch (IOException e) {e.printStackTrace();}
        loseText.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        loseText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loseText.setText("You Hit A Mine!");

        btnMainMenu.setBackground(new java.awt.Color(200, 200, 200));
        btnMainMenu.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnMainMenu.setContentAreaFilled(false);
        btnMainMenu.setOpaque(true);
        btnMainMenu.setVerifyInputWhenFocusTarget(false);
        btnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseExited(evt);
            }
        });
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        btnNewGame.setBackground(new java.awt.Color(200, 200, 200));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnNewGame.setContentAreaFilled(false);
        btnNewGame.setOpaque(true);
        btnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewGameMouseExited(evt);
            }
        });
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });
        
        company.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 20)); // NOI18N
        company.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        company.setText("Copyright \u00a9 2020, VMSOGROUP2. All Rights Reserved ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(endGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loseText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mineImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(company, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(endGame, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mineImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loseText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(company)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(150, 150, 150));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 35));
    }                                        

    private void btnNewGameMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(200, 200, 200));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 30));
    }       

    private void btnNewGameMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(50, 50, 50));
    }
    
    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewGameActionPerformed
    
    private void btnMainMenuMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        btnMainMenu.setBackground(new java.awt.Color(150, 150, 150));
        btnMainMenu.setFont(new java.awt.Font("Agency FB", 0, 35));
    }                                        

    private void btnMainMenuMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        btnMainMenu.setBackground(new java.awt.Color(200, 200, 200));
        btnMainMenu.setFont(new java.awt.Font("Agency FB", 0, 30));
    }

    private void btnMainMenuMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        btnMainMenu.setBackground(new java.awt.Color(50, 50, 50));
    }

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoseScreen().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel endGame;
    private javax.swing.JLabel mineImage;
    private javax.swing.JLabel loseText;
    private javax.swing.JLabel company;
    // End of variables declaration//GEN-END:variables
}
