/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/Minesweeper 
 *
 * modified     20201110
 * date         20201104
 * @filename	MainMenu.java
 * @author      hkamal
 * @version     1.0
 * @see         Main menu screen
 */

package minesweeper;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.imageio.ImageIO;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewGame = new javax.swing.JButton();
        btnInstructions = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        lblCompany = new javax.swing.JLabel();
        lblMainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    	int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
    	int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
    	this.setLocation(x, y);

        btnNewGame.setBackground(new java.awt.Color(200, 200, 200));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnNewGame.setContentAreaFilled(false);
        btnNewGame.setOpaque(true);
        btnNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewGameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewGameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewGameMouseExited(evt);
            }
        });
        getContentPane().add(btnNewGame);
        btnNewGame.setBounds(140, 320, 420, 50);
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnInstructions.setBackground(new java.awt.Color(200, 200, 200));
        btnInstructions.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnInstructions.setText("Instructions");
        btnInstructions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnInstructions.setContentAreaFilled(false);
        btnInstructions.setOpaque(true);
        btnInstructions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInstructionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInstructionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInstructionsMouseExited(evt);
            }
        });
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstructions);
        btnInstructions.setBounds(140, 380, 420, 50);

        btnExit.setBackground(new java.awt.Color(200, 200, 200));
        btnExit.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnExit.setContentAreaFilled(false);
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(360, 440, 200, 50);

        btnAbout.setBackground(new java.awt.Color(200, 200, 200));
        btnAbout.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnAbout.setContentAreaFilled(false);
        btnAbout.setOpaque(true);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbout);
        btnAbout.setBounds(140, 440, 210, 50);

        lblCompany.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(255, 255, 255));
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("Copyright \u00a9 2020, VMSOGROUP2. All Rights Reserved");
        lblCompany.setMaximumSize(new java.awt.Dimension(700, 700));
        lblCompany.setMinimumSize(new java.awt.Dimension(700, 700));
        lblCompany.setPreferredSize(new java.awt.Dimension(700, 700));
        getContentPane().add(lblCompany);
        lblCompany.setBounds(0, 570, 700, 130);
        try {
            lblMainImage.setIcon(new javax.swing.ImageIcon(ImageIO.read(getClass().getResourceAsStream("assets/background.png")))); // http://www.sireasgallery.com/icon/minesweeper/Mine
        }
        catch (IOException e) {e.printStackTrace();}
        lblMainImage.setText("lblMainImage");
        getContentPane().add(lblMainImage);
        lblMainImage.setBounds(0, 0, 700, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewGameMouseEntered
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(150, 150, 150));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 45));
    }//GEN-LAST:event_btnNewGameMouseEntered
    
    private void btnNewGameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewGameMouseExited
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(200, 200, 200));
        btnNewGame.setFont(new java.awt.Font("Agency FB", 0, 35));
    }//GEN-LAST:event_btnNewGameMouseExited

    private void btnNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewGameMouseClicked
        // TODO add your handling code here:
        btnNewGame.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnNewGameMouseClicked

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewGameActionPerformed
    
    private void btnInstructionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstructionsMouseEntered
        // TODO add your handling code here:
        btnInstructions.setBackground(new java.awt.Color(150, 150, 150));
        btnInstructions.setFont(new java.awt.Font("Agency FB", 0, 45));
    }//GEN-LAST:event_btnInstructionsMouseEntered

    private void btnInstructionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstructionsMouseExited
        // TODO add your handling code here:
        btnInstructions.setBackground(new java.awt.Color(200, 200, 200));
        btnInstructions.setFont(new java.awt.Font("Agency FB", 0, 35));
    }//GEN-LAST:event_btnInstructionsMouseExited

    private void btnInstructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInstructionsMouseClicked
        // TODO add your handling code here:
        btnInstructions.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnInstructionsMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        // TODO add your handling code here:
        btnAbout.setBackground(new java.awt.Color(150, 150, 150));
        btnAbout.setFont(new java.awt.Font("Agency FB", 0, 45));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        // TODO add your handling code here:
        btnAbout.setBackground(new java.awt.Color(200, 200, 200));
        btnAbout.setFont(new java.awt.Font("Agency FB", 0, 35));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        btnAbout.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new java.awt.Color(150, 150, 150));
        btnExit.setFont(new java.awt.Font("Agency FB", 0, 45));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(new java.awt.Color(200, 200, 200));
        btnExit.setFont(new java.awt.Font("Agency FB", 0, 35));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        btnExit.setBackground(new java.awt.Color(50, 50, 50));
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new Instruction().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnAbout;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblMainImage;
    // End of variables declaration//GEN-END:variables
}
